---

- hosts: all
  become: true
  tasks:

  - name: Install apache & php packages
#    apt:
    package: # this module will use the correct package manager depending of the guet'OS  (i.e Ubuntu=> apt, CentOs=>dnf)
        name:
             - "{{ apache_package }}" # this is a variable
             - "{{ php_package }}"
        state: latest
        update_cache: yes
#    when: ansible_distribution == "Ubuntu"
#   when: ansible_distribution in ["Debian","Ubuntu"] # for multi-dist types
# ths 'ansible_distribution' var, commes from the 'gather_facts' step

