---

- hosts: all
  become: true
  tasks:
#  pre_tasks: # we can force some tasks to run before other with this option
  - name: Install updates (Ubuntu)
    when: ansible_distribution == "Ubuntu" # ths 'ansible_distribution' var, commes from the 'gather_facts' step
    apt:
      upgrade: dist
      update_cache: yes


- hosts: web_servers # value from the inventory file
  become: true
  tasks:
  - name: Install apache & php packages
    when: ansible_distribution == "Ubuntu"
    package: # this module will use the correct package manager depending of the guet'OS  (i.e Ubuntu=> apt, CentOs=>dnf)
        name:
             - "{{ apache_package }}" # this is a variable from the inventory file
             - "{{ php_package }}"
        state: latest
# when: ansible_distribution == "Ubuntu"
# when: ansible_distribution in ["Debian","Ubuntu"] # for multi-dist types

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package
    apt:
        name: mariadb-server
        state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    package: # i use package to handle diff linux dist
        name: samba
        state: latest
