---
- hosts: all
  become: true # to become a root user
  pre_tasks: # we can force some tasks to run before other ones with this option

  - name: Update repo cache (CentOS)
    tags: always
    when: ansible_distribution == "CentOS"
    dnf:
      update_cache: yes
    changed_when: false # with this option in place, even if the host's cache is updated, we don't want to see the "changed = 1"  in the final log of ansible (a cleaner output at then end of ansible execution)

  - name: Update repo cache (Ubuntu)
    tags: always # this tags is used to always run the play
    when: ansible_distribution == "Ubuntu" # ths 'ansible_distribution' var, commes from the 'gather_facts' step
    apt:
      update_cache: yes
    changed_when: false # with this option in place, even if the host's cache is updated, we don't want to see the "changed = 1"  in the final log of ansible


- hosts: all
  become: true
  roles:
    - base # this role is the name of a dir i created under ./roles

- hosts: workstations  # this is indicated in the inventory file
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
