- name: Install the mariadb server package  (CentOS)
  when: ansible_distribution == "CentOS"
  tags: db,mariadb,centos
  dnf:
    name: mariadb
    state: latest

- name: Install the mariadb server package  (Ubuntu)
  when: ansible_distribution == "Ubuntu"
  tags: db,mariadb,ubuntu
  apt:
     name: mariadb-server
     state: latest
