- name: Install unzip
  package:
     name: unzip

- name: Install terraform
  unarchive: # this is why we installed unzip !
        remote_src: yes
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755
